[tool.semantic_release]
version_source = "tag"
branch = "main"
upload_to_pypi = false
repository = "https://github.com/Tushar98644/Trucept"

[changelog.default_templates]
changelog_file = "CHANGELOG.md"